# Form implementation generated from reading ui file 'HO_UME.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HO_UME(object):
    def setupUi(self, HO_UME):
        HO_UME.setObjectName("HO_UME")
        HO_UME.resize(697, 566)
        HO_UME.setStyleSheet("QPushButton {\n"
" font-size: 16px;\n"
" color: rgb(255, 255, 255);\n"
" background-color:rgb(255, 85, 255)\n"
"}\n"
"\n"
"QLabel {\n"
"  font-size: 12px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(HO_UME)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=HO_UME)
        self.label_2.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=HO_UME)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_ho = QtWidgets.QLineEdit(parent=HO_UME)
        self.lineEdit_ho.setObjectName("lineEdit_ho")
        self.horizontalLayout_4.addWidget(self.lineEdit_ho)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=HO_UME)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_A1A2 = QtWidgets.QLineEdit(parent=HO_UME)
        self.lineEdit_A1A2.setObjectName("lineEdit_A1A2")
        self.horizontalLayout_5.addWidget(self.lineEdit_A1A2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(2, 2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=HO_UME)
        self.label.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_choose_dir = QtWidgets.QPushButton(parent=HO_UME)
        self.pushButton_choose_dir.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_choose_dir.setObjectName("pushButton_choose_dir")
        self.horizontalLayout.addWidget(self.pushButton_choose_dir)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_nr = QtWidgets.QRadioButton(parent=HO_UME)
        self.radioButton_nr.setEnabled(True)
        self.radioButton_nr.setCheckable(True)
        self.radioButton_nr.setChecked(True)
        self.radioButton_nr.setObjectName("radioButton_nr")
        self.horizontalLayout_3.addWidget(self.radioButton_nr)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.radioButton_lte = QtWidgets.QRadioButton(parent=HO_UME)
        self.radioButton_lte.setEnabled(True)
        self.radioButton_lte.setCheckable(True)
        self.radioButton_lte.setChecked(False)
        self.radioButton_lte.setObjectName("radioButton_lte")
        self.horizontalLayout_3.addWidget(self.radioButton_lte)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.textBrowser_log = QtWidgets.QTextBrowser(parent=HO_UME)
        self.textBrowser_log.setEnabled(True)
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.gridLayout.addWidget(self.textBrowser_log, 7, 0, 1, 1)
        self.pushButton_doandsave = QtWidgets.QPushButton(parent=HO_UME)
        self.pushButton_doandsave.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_doandsave.setObjectName("pushButton_doandsave")
        self.gridLayout.addWidget(self.pushButton_doandsave, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget_excel_paths = QtWidgets.QListWidget(parent=HO_UME)
        self.listWidget_excel_paths.setEnabled(True)
        self.listWidget_excel_paths.setObjectName("listWidget_excel_paths")
        self.horizontalLayout_2.addWidget(self.listWidget_excel_paths)
        self.pushButton_remove_excel = QtWidgets.QPushButton(parent=HO_UME)
        self.pushButton_remove_excel.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_remove_excel.setObjectName("pushButton_remove_excel")
        self.horizontalLayout_2.addWidget(self.pushButton_remove_excel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)

        self.retranslateUi(HO_UME)
        QtCore.QMetaObject.connectSlotsByName(HO_UME)

    def retranslateUi(self, HO_UME):
        _translate = QtCore.QCoreApplication.translate
        HO_UME.setWindowTitle(_translate("HO_UME", "参数核查"))
        self.label_2.setText(_translate("HO_UME", "请移除不需要的文件"))
        self.label_3.setText(_translate("HO_UME", "切换对象标识"))
        self.lineEdit_ho.setText(_translate("HO_UME", "default"))
        self.label_4.setText(_translate("HO_UME", "A1A2对象标识"))
        self.lineEdit_A1A2.setText(_translate("HO_UME", "1"))
        self.label.setText(_translate("HO_UME", "请选择要核查的文件"))
        self.pushButton_choose_dir.setText(_translate("HO_UME", "选择文件"))
        self.radioButton_nr.setText(_translate("HO_UME", "NR-NR"))
        self.radioButton_lte.setText(_translate("HO_UME", "NR_LTE"))
        self.pushButton_doandsave.setText(_translate("HO_UME", "执行并保存"))
        self.pushButton_remove_excel.setText(_translate("HO_UME", "移除文件"))
