# Form implementation generated from reading ui file 'neighbor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_neighbor(object):
    def setupUi(self, neighbor):
        neighbor.setObjectName("neighbor")
        neighbor.resize(697, 566)
        neighbor.setStyleSheet("QPushButton {\n"
" font-size: 16px;\n"
" color: rgb(255, 255, 255);\n"
" background-color:rgb(255, 85, 255)\n"
"}\n"
"\n"
"QLabel {\n"
"  font-size: 12px;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(neighbor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=neighbor)
        self.label_2.setStyleSheet("font: 11pt \"Microsoft YaHei UI\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton_cell_ex = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_cell_ex.setObjectName("pushButton_cell_ex")
        self.horizontalLayout.addWidget(self.pushButton_cell_ex)
        self.pushButton_choose_ycell = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_choose_ycell.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_choose_ycell.setObjectName("pushButton_choose_ycell")
        self.horizontalLayout.addWidget(self.pushButton_choose_ycell)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 4)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=neighbor)
        self.label.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton_choose_cell = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_choose_cell.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_choose_cell.setObjectName("pushButton_choose_cell")
        self.horizontalLayout_3.addWidget(self.pushButton_choose_cell)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=neighbor)
        self.label_3.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pushButton_choose_nei = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_choose_nei.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_choose_nei.setObjectName("pushButton_choose_nei")
        self.horizontalLayout_2.addWidget(self.pushButton_choose_nei)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.textBrowser_log = QtWidgets.QTextBrowser(parent=neighbor)
        self.textBrowser_log.setEnabled(True)
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.gridLayout_2.addWidget(self.textBrowser_log, 7, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 6, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_hx = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_hx.setEnabled(True)
        self.pushButton_hx.setAccessibleName("")
        self.pushButton_hx.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_hx.setObjectName("pushButton_hx")
        self.gridLayout.addWidget(self.pushButton_hx, 1, 0, 1, 1)
        self.pushButton_m3 = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_m3.setEnabled(True)
        self.pushButton_m3.setAccessibleName("")
        self.pushButton_m3.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_m3.setObjectName("pushButton_m3")
        self.gridLayout.addWidget(self.pushButton_m3, 2, 2, 1, 1)
        self.pushButton_ct = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_ct.setEnabled(True)
        self.pushButton_ct.setAccessibleName("")
        self.pushButton_ct.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_ct.setObjectName("pushButton_ct")
        self.gridLayout.addWidget(self.pushButton_ct, 1, 2, 1, 1)
        self.pushButton_ex = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_ex.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_ex.setObjectName("pushButton_ex")
        self.gridLayout.addWidget(self.pushButton_ex, 0, 0, 1, 1)
        self.pushButton_num = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_num.setEnabled(True)
        self.pushButton_num.setAccessibleName("")
        self.pushButton_num.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_num.setObjectName("pushButton_num")
        self.gridLayout.addWidget(self.pushButton_num, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.pushButton_dy = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_dy.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_dy.setObjectName("pushButton_dy")
        self.gridLayout.addWidget(self.pushButton_dy, 0, 1, 1, 1)
        self.pushButton_nei_red = QtWidgets.QPushButton(parent=neighbor)
        self.pushButton_nei_red.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";\n"
"background-color: rgb(0, 170, 255);")
        self.pushButton_nei_red.setObjectName("pushButton_nei_red")
        self.gridLayout.addWidget(self.pushButton_nei_red, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 4, 0, 1, 1)

        self.retranslateUi(neighbor)
        QtCore.QMetaObject.connectSlotsByName(neighbor)

    def retranslateUi(self, neighbor):
        _translate = QtCore.QCoreApplication.translate
        neighbor.setWindowTitle(_translate("neighbor", "邻区核查"))
        self.label_2.setText(_translate("neighbor", "异厂家或非中兴网管导出的小区信息"))
        self.pushButton_cell_ex.setText(_translate("neighbor", "模板导出"))
        self.pushButton_choose_ycell.setText(_translate("neighbor", "导入异厂家小区信息"))
        self.label.setText(_translate("neighbor", "请选择要导入的小区信息excel"))
        self.pushButton_choose_cell.setText(_translate("neighbor", "导入小区信息(中兴网管原表)"))
        self.label_3.setText(_translate("neighbor", "请选择要导入的邻区信息excel"))
        self.pushButton_choose_nei.setText(_translate("neighbor", "导入邻区信息(中兴网管原表)"))
        self.pushButton_hx.setText(_translate("neighbor", "PCI混淆"))
        self.pushButton_m3.setText(_translate("neighbor", "M3核查"))
        self.pushButton_ct.setText(_translate("neighbor", "PCI冲突"))
        self.pushButton_ex.setText(_translate("neighbor", "外部一致性核查"))
        self.pushButton_num.setText(_translate("neighbor", "邻区数量"))
        self.pushButton_dy.setText(_translate("neighbor", "冗余外部核查"))
        self.pushButton_nei_red.setText(_translate("neighbor", "冗余邻区核查"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    neighbor = QtWidgets.QDialog()
    ui = Ui_neighbor()
    ui.setupUi(neighbor)
    neighbor.show()
    sys.exit(app.exec())
