# Form implementation generated from reading ui file 'excel_inx2col.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Excelinx2col(object):
    def setupUi(self, Excelinx2col):
        Excelinx2col.setObjectName("Excelinx2col")
        Excelinx2col.resize(709, 662)
        Excelinx2col.setStyleSheet("* {\n"
"  font-size: 16px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Excelinx2col)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Excelinx2col)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listWidget_inx = QtWidgets.QListWidget(parent=Excelinx2col)
        self.listWidget_inx.setObjectName("listWidget_inx")
        self.verticalLayout.addWidget(self.listWidget_inx)
        self.pushButton_remove_inx = QtWidgets.QPushButton(parent=Excelinx2col)
        self.pushButton_remove_inx.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_remove_inx.setObjectName("pushButton_remove_inx")
        self.verticalLayout.addWidget(self.pushButton_remove_inx)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=Excelinx2col)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listWidget_value = QtWidgets.QListWidget(parent=Excelinx2col)
        self.listWidget_value.setObjectName("listWidget_value")
        self.verticalLayout_2.addWidget(self.listWidget_value)
        self.pushButton_remove_col = QtWidgets.QPushButton(parent=Excelinx2col)
        self.pushButton_remove_col.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_remove_col.setObjectName("pushButton_remove_col")
        self.verticalLayout_2.addWidget(self.pushButton_remove_col)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton_do_inx2col = QtWidgets.QPushButton(parent=Excelinx2col)
        self.pushButton_do_inx2col.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_do_inx2col.setObjectName("pushButton_do_inx2col")
        self.horizontalLayout_5.addWidget(self.pushButton_do_inx2col)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pushButton_do_col2inx = QtWidgets.QPushButton(parent=Excelinx2col)
        self.pushButton_do_col2inx.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_do_col2inx.setObjectName("pushButton_do_col2inx")
        self.horizontalLayout_5.addWidget(self.pushButton_do_col2inx)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_output_dir = QtWidgets.QLineEdit(parent=Excelinx2col)
        self.lineEdit_output_dir.setStyleSheet("* {\n"
"  font-size:10px;\n"
"}")
        self.lineEdit_output_dir.setObjectName("lineEdit_output_dir")
        self.horizontalLayout_3.addWidget(self.lineEdit_output_dir)
        self.pushButton_choose_dir = QtWidgets.QPushButton(parent=Excelinx2col)
        self.pushButton_choose_dir.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_choose_dir.setObjectName("pushButton_choose_dir")
        self.horizontalLayout_3.addWidget(self.pushButton_choose_dir)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Excelinx2col)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_choose_excel = QtWidgets.QPushButton(parent=Excelinx2col)
        self.pushButton_choose_excel.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_choose_excel.setObjectName("pushButton_choose_excel")
        self.horizontalLayout.addWidget(self.pushButton_choose_excel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.lineEdit_excel_path = QtWidgets.QLineEdit(parent=Excelinx2col)
        self.lineEdit_excel_path.setStyleSheet("* {\n"
"  font-size:10px;\n"
"}")
        self.lineEdit_excel_path.setObjectName("lineEdit_excel_path")
        self.gridLayout.addWidget(self.lineEdit_excel_path, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(3, 8)
        self.lineEdit_excel_path.raise_()
        self.retranslateUi(Excelinx2col)
        QtCore.QMetaObject.connectSlotsByName(Excelinx2col)

    def retranslateUi(self, Excelinx2col):
        _translate = QtCore.QCoreApplication.translate
        Excelinx2col.setWindowTitle(_translate("Excelinx2col", "Excel行列转换"))
        self.label_2.setText(_translate("Excelinx2col", "选择需要转换的列（index）"))
        self.pushButton_remove_inx.setText(_translate("Excelinx2col", "移除不需要的列"))
        self.label_3.setText(_translate("Excelinx2col", "选择需要转换的列（值）"))
        self.pushButton_remove_col.setText(_translate("Excelinx2col", "移除不需要的列"))
        self.pushButton_do_inx2col.setText(_translate("Excelinx2col", "行转列"))
        self.pushButton_do_col2inx.setText(_translate("Excelinx2col", "列转行"))
        self.pushButton_choose_dir.setWhatsThis(_translate("Excelinx2col", "<html><head/><body><p>background-color: rgb(255, 0, 255);</p><p>color: rgb(255, 255, 255);</p></body></html>"))
        self.pushButton_choose_dir.setText(_translate("Excelinx2col", "选择输出的目录"))
        self.label.setText(_translate("Excelinx2col", "请选择要转换的文件："))
        self.pushButton_choose_excel.setText(_translate("Excelinx2col", "选择文件"))
