# Form implementation generated from reading ui file 'excel_merger.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExcelMerger(object):
    def setupUi(self, ExcelMerger):
        ExcelMerger.setObjectName("ExcelMerger")
        ExcelMerger.resize(698, 566)
        ExcelMerger.setStyleSheet("QPushButton {\n"
" font-size: 16px;\n"
" color: rgb(255, 255, 255);\n"
" background-color:rgb(255, 85, 255)\n"
"}\n"
"\n"
"QLabel {\n"
"  font-size: 16px;\n"
"  font-weight: bold;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(ExcelMerger)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=ExcelMerger)
        self.label.setStyleSheet("font: 75 9pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_choose_dir = QtWidgets.QPushButton(parent=ExcelMerger)
        self.pushButton_choose_dir.setObjectName("pushButton_choose_dir")
        self.horizontalLayout.addWidget(self.pushButton_choose_dir)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.radioButton = QtWidgets.QRadioButton(parent=ExcelMerger)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=ExcelMerger)
        self.label_3.setStyleSheet("font: 75 9pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(parent=ExcelMerger)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=ExcelMerger)
        self.label_2.setStyleSheet("font: 75 9pt \"Agency FB\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget_excel_paths = QtWidgets.QListWidget(parent=ExcelMerger)
        self.listWidget_excel_paths.setObjectName("listWidget_excel_paths")
        self.horizontalLayout_2.addWidget(self.listWidget_excel_paths)
        self.pushButton_remove_excel = QtWidgets.QPushButton(parent=ExcelMerger)
        self.pushButton_remove_excel.setObjectName("pushButton_remove_excel")
        self.horizontalLayout_2.addWidget(self.pushButton_remove_excel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.pushButton_domerge_andsave = QtWidgets.QPushButton(parent=ExcelMerger)
        self.pushButton_domerge_andsave.setObjectName("pushButton_domerge_andsave")
        self.gridLayout.addWidget(self.pushButton_domerge_andsave, 5, 0, 1, 1)

        self.retranslateUi(ExcelMerger)
        QtCore.QMetaObject.connectSlotsByName(ExcelMerger)

    def retranslateUi(self, ExcelMerger):
        _translate = QtCore.QCoreApplication.translate
        ExcelMerger.setWindowTitle(_translate("ExcelMerger", "合并Excel文件"))
        self.label.setText(_translate("ExcelMerger", "请选择要合并的文件"))
        self.pushButton_choose_dir.setText(_translate("ExcelMerger", "选择文件"))
        self.radioButton.setText(_translate("ExcelMerger", "把各文件中Worksheet名相同的表格合并到一个sheet中"))
        self.label_3.setText(_translate("ExcelMerger", "文件表头行数"))
        self.comboBox.setItemText(0, _translate("ExcelMerger", "1"))
        self.comboBox.setItemText(1, _translate("ExcelMerger", "2"))
        self.comboBox.setItemText(2, _translate("ExcelMerger", "3"))
        self.comboBox.setItemText(3, _translate("ExcelMerger", "4"))
        self.comboBox.setItemText(4, _translate("ExcelMerger", "5"))
        self.comboBox.setItemText(5, _translate("ExcelMerger", "6"))
        self.comboBox.setItemText(6, _translate("ExcelMerger", "7"))
        self.comboBox.setItemText(7, _translate("ExcelMerger", "8"))
        self.label_2.setText(_translate("ExcelMerger", "请移除不需要的文件"))
        self.pushButton_remove_excel.setText(_translate("ExcelMerger", "移除文件"))
        self.pushButton_domerge_andsave.setText(_translate("ExcelMerger", "执行合并保存结果文件"))
