# Form implementation generated from reading ui file 'ui_epms.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_emps(object):
    def setupUi(self, Dialog_emps):
        Dialog_emps.setObjectName("Dialog_emps")
        Dialog_emps.resize(643, 455)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_emps)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog_emps)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_username = QtWidgets.QLineEdit(parent=Dialog_emps)
        self.lineEdit_username.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout.addWidget(self.lineEdit_username)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=Dialog_emps)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=Dialog_emps)
        self.lineEdit_password.setStyleSheet("font: 12pt \"Microsoft YaHei UI\";")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_2.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.pushButton_login = QtWidgets.QPushButton(parent=Dialog_emps)
        self.pushButton_login.setStyleSheet("\n"
"background-color: rgb(0, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: bold;")
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout_3.addWidget(self.pushButton_login)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.pushButton_get_proName = QtWidgets.QPushButton(parent=Dialog_emps)
        self.pushButton_get_proName.setObjectName("pushButton_get_proName")
        self.verticalLayout_4.addWidget(self.pushButton_get_proName)
        self.label = QtWidgets.QLabel(parent=Dialog_emps)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.textBrowser_log = QtWidgets.QTextBrowser(parent=Dialog_emps)
        self.textBrowser_log.setObjectName("textBrowser_log")
        self.verticalLayout_4.addWidget(self.textBrowser_log)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout_4.setStretch(3, 8)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=Dialog_emps)
        self.label_3.setStyleSheet("font: 75 9pt \"Agency FB\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.pushButton_remove_proj = QtWidgets.QPushButton(parent=Dialog_emps)
        self.pushButton_remove_proj.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: bold;")
        self.pushButton_remove_proj.setObjectName("pushButton_remove_proj")
        self.horizontalLayout_4.addWidget(self.pushButton_remove_proj)
        self.pushButton_do = QtWidgets.QPushButton(parent=Dialog_emps)
        self.pushButton_do.setStyleSheet("\n"
"background-color: rgb(0, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: bold;")
        self.pushButton_do.setObjectName("pushButton_do")
        self.horizontalLayout_4.addWidget(self.pushButton_do)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.listWidget_project = QtWidgets.QListWidget(parent=Dialog_emps)
        self.listWidget_project.setObjectName("listWidget_project")
        self.verticalLayout_2.addWidget(self.listWidget_project)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 3)

        self.retranslateUi(Dialog_emps)
        QtCore.QMetaObject.connectSlotsByName(Dialog_emps)

    def retranslateUi(self, Dialog_emps):
        _translate = QtCore.QCoreApplication.translate
        Dialog_emps.setWindowTitle(_translate("Dialog_emps", "epms站点设备统计工具"))
        self.label_2.setText(_translate("Dialog_emps", "请输入账号"))
        self.label_4.setText(_translate("Dialog_emps", "请输入密码"))
        self.pushButton_login.setText(_translate("Dialog_emps", "登录"))
        self.pushButton_get_proName.setText(_translate("Dialog_emps", "获取全部项目"))
        self.label.setText(_translate("Dialog_emps", "日志"))
        self.label_3.setText(_translate("Dialog_emps", "请移除不需要的项目"))
        self.pushButton_remove_proj.setText(_translate("Dialog_emps", "移除项目"))
        self.pushButton_do.setText(_translate("Dialog_emps", "下载分析数据并保存"))
