# Form implementation generated from reading ui file 'Ui_PDF.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PDFHand(object):
    def setupUi(self, PDFHand):
        PDFHand.setObjectName("PDFHand")
        PDFHand.resize(692, 519)
        self.gridLayout = QtWidgets.QGridLayout(PDFHand)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_do_merge = QtWidgets.QPushButton(parent=PDFHand)
        self.pushButton_do_merge.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_do_merge.setObjectName("pushButton_do_merge")
        self.verticalLayout_2.addWidget(self.pushButton_do_merge)
        self.label = QtWidgets.QLabel(parent=PDFHand)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit_step = QtWidgets.QLineEdit(parent=PDFHand)
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.verticalLayout_2.addWidget(self.lineEdit_step)
        self.pushButton_do_split = QtWidgets.QPushButton(parent=PDFHand)
        self.pushButton_do_split.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_do_split.setObjectName("pushButton_do_split")
        self.verticalLayout_2.addWidget(self.pushButton_do_split)
        self.label_2 = QtWidgets.QLabel(parent=PDFHand)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_end = QtWidgets.QLineEdit(parent=PDFHand)
        self.lineEdit_end.setObjectName("lineEdit_end")
        self.verticalLayout_2.addWidget(self.lineEdit_end)
        self.label_3 = QtWidgets.QLabel(parent=PDFHand)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_start = QtWidgets.QLineEdit(parent=PDFHand)
        self.lineEdit_start.setText("")
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.verticalLayout_2.addWidget(self.lineEdit_start)
        self.radioButton = QtWidgets.QRadioButton(parent=PDFHand)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.lineEdit_list = QtWidgets.QLineEdit(parent=PDFHand)
        self.lineEdit_list.setObjectName("lineEdit_list")
        self.verticalLayout_2.addWidget(self.lineEdit_list)
        self.pushButton_do_convert = QtWidgets.QPushButton(parent=PDFHand)
        self.pushButton_do_convert.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_do_convert.setObjectName("pushButton_do_convert")
        self.verticalLayout_2.addWidget(self.pushButton_do_convert)
        self.pushButton_pdf2word = QtWidgets.QPushButton(parent=PDFHand)
        self.pushButton_pdf2word.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_pdf2word.setObjectName("pushButton_pdf2word")
        self.verticalLayout_2.addWidget(self.pushButton_pdf2word)
        self.pushButton_pdf2low = QtWidgets.QPushButton(parent=PDFHand)
        self.pushButton_pdf2low.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_pdf2low.setObjectName("pushButton_pdf2low")
        self.verticalLayout_2.addWidget(self.pushButton_pdf2low)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_choose_dir = QtWidgets.QPushButton(parent=PDFHand)
        self.pushButton_choose_dir.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_choose_dir.setObjectName("pushButton_choose_dir")
        self.verticalLayout.addWidget(self.pushButton_choose_dir)
        self.listWidget_pdf_paths = QtWidgets.QListWidget(parent=PDFHand)
        self.listWidget_pdf_paths.setObjectName("listWidget_pdf_paths")
        self.verticalLayout.addWidget(self.listWidget_pdf_paths)
        self.pushButton_remove_pdf = QtWidgets.QPushButton(parent=PDFHand)
        self.pushButton_remove_pdf.setStyleSheet("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_remove_pdf.setObjectName("pushButton_remove_pdf")
        self.verticalLayout.addWidget(self.pushButton_remove_pdf)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(PDFHand)
        QtCore.QMetaObject.connectSlotsByName(PDFHand)

    def retranslateUi(self, PDFHand):
        _translate = QtCore.QCoreApplication.translate
        PDFHand.setWindowTitle(_translate("PDFHand", "PDF处理"))
        self.pushButton_do_merge.setText(_translate("PDFHand", "pdf合并"))
        self.label.setText(_translate("PDFHand", "拆分步长"))
        self.lineEdit_step.setText(_translate("PDFHand", "10"))
        self.pushButton_do_split.setText(_translate("PDFHand", "pdf拆分"))
        self.label_2.setText(_translate("PDFHand", "转换开始页码"))
        self.lineEdit_end.setText(_translate("PDFHand", "0"))
        self.label_3.setText(_translate("PDFHand", "转换结束页码"))
        self.radioButton.setText(_translate("PDFHand", "按固定页数转换"))
        self.lineEdit_list.setText(_translate("PDFHand", "1,2"))
        self.pushButton_do_convert.setText(_translate("PDFHand", "pdf转word"))
        self.pushButton_pdf2word.setText(_translate("PDFHand", "pdf转word(可编辑)"))
        self.pushButton_pdf2low.setText(_translate("PDFHand", "pdf压缩"))
        self.pushButton_choose_dir.setText(_translate("PDFHand", "选择文件"))
        self.pushButton_remove_pdf.setText(_translate("PDFHand", "移除文件"))
